// src/app/terms/page.tsx
"use client";

export default function TermsPage() {
  const UPDATED = "27 August 2025";

  return (
    <main className="container section prose prose-slate max-w-3xl">
      <h1 className="heading-2">Terms of Service</h1>
      <p className="small text-slate-500">Last updated: {UPDATED}</p>

      <p>
        These Terms of Service (“<strong>Terms</strong>”) govern your access to and use of the <strong>PropVisions</strong> website and services (the “<strong>Service</strong>”).
        By using the Service, you agree to these Terms. If you use the Service on behalf of a company, you represent that you are authorised to bind that company, and “you” refers to both you and that company.
      </p>

      <h2 id="definitions">1. Definitions</h2>
      <ul>
        <li><strong>Inputs</strong>: content you submit (e.g., property URLs, notes, assumptions).</li>
        <li><strong>Outputs</strong>: content generated by the Service (e.g., refurb scopes, valuations, rent bands, financials, PDFs/Excels).</li>
        <li><strong>Beta</strong>: pre-release features, modules, or environments subject to change and availability.</li>
      </ul>

      <h2 id="changes">2. Changes to the Service & Terms</h2>
      <p>We may update the Service and these Terms from time to time (e.g., to add features, address legal or security requirements). If changes are material, we will provide reasonable notice. Continued use after changes constitutes acceptance.</p>

      <h2 id="eligibility">3. Eligibility & account</h2>
      <p>You must be at least 18 and able to form a binding contract. You are responsible for your account, credentials, and activity, and must keep your information accurate.</p>

      <h2 id="beta">4. Beta disclaimer</h2>
      <p>
        The Service is currently in Beta. Features may be rate-limited, gated, or unavailable (e.g., portal ingestion for Rightmove/Zoopla). Beta components are provided “as is”; performance and accuracy may vary. We may modify or discontinue Beta features at any time.
      </p>

      <h2 id="acceptable-use">5. Acceptable use</h2>
      <p>You will not (nor authorise others to):</p>
      <ul>
        <li>Use the Service unlawfully, to infringe rights, or to access unauthorised data.</li>
        <li>Scrape, harvest, or store third-party content in breach of their terms or applicable law.</li>
        <li>Attempt to bypass technical restrictions or rate limits; probe or scan systems without consent.</li>
        <li>Introduce malware or interfere with the integrity or performance of the Service.</li>
        <li>Use Outputs to mislead (e.g., presenting estimates as certified valuations) or for high-risk decisions without validation.</li>
      </ul>

      <h2 id="inputs-outputs">6. Inputs, Outputs & licence</h2>
      <ul>
        <li><strong>Your Inputs</strong>: you retain rights in your Inputs. You grant us a non-exclusive, worldwide, royalty-free licence to process your Inputs and Outputs to provide, maintain, secure, and improve the Service (including quality, analytics in aggregate, and abuse detection).</li>
        <li><strong>Outputs</strong>: subject to these Terms and third-party rights, we assign to you our rights, if any, in Outputs we generate for you. You are responsible for verifying Outputs and for any use thereof.</li>
        <li><strong>Proprietary rights</strong>: we and our licensors own the Service and all related IP (software, UI, brand). No rights are granted except as expressly provided.</li>
      </ul>

      <h2 id="ai-disclaimer">7. AI/estimates & non-advice</h2>
      <p>
        Outputs are estimates generated from your Inputs, public signals, priors, and programmatic rules. They are <strong>not financial advice</strong>, not a recommendation to buy/sell assets, and not a RICS valuation. You must perform your own due diligence. We do not guarantee accuracy, completeness, or fitness for any particular purpose.
      </p>
      <p className="small text-slate-500">PropVisions is not authorised or regulated by the FCA. The Service is a decision-support tool only.</p>

      <h2 id="third-parties">8. Third-party services & content</h2>
      <p>
        The Service may reference or interface with third-party websites, APIs, datasets, or tools. We are not responsible for their availability, performance, or accuracy, and do not endorse them. Your use of third-party services may be governed by their terms and policies.
      </p>

      <h2 id="fees">9. Plans, fees & taxes</h2>
      <p>
        Fees (when applicable) are billed by our payment provider (e.g., Stripe). You authorise us to charge your payment method for subscription periods, usage, and applicable taxes. Unless required by law, fees are non-refundable once a billing period starts. We may change prices with prior notice for subsequent periods.
      </p>

      <h2 id="privacy">10. Privacy</h2>
      <p>
        Our <a href="/privacy">Privacy Policy</a> explains how we process personal data. If we process personal data as processor on your behalf (B2B), our data processing terms (DPA) apply and are available on request.
      </p>

      <h2 id="confidentiality">11. Confidentiality</h2>
      <p>
        Each party may access the other’s non-public information (“Confidential Information”). A party will: (a) use the other’s Confidential Information only to perform under these Terms; (b) protect it using reasonable safeguards; and (c) not disclose it except to personnel and subprocessors bound by similar obligations, or as required by law.
      </p>

      <h2 id="availability">12. Availability, support & force majeure</h2>
      <p>
        We aim for high availability but do not guarantee uninterrupted service. Maintenance windows, outages, or third-party failures may occur. Neither party is liable for delays or failures due to events beyond reasonable control (force majeure).
      </p>

      <h2 id="indemnity">13. Indemnity</h2>
      <p>
        You will defend, indemnify, and hold us harmless from claims arising out of (a) your Inputs; (b) your use of the Service in breach of these Terms or law; or (c) your violation of third-party rights, including intellectual property or privacy rights.
      </p>

      <h2 id="liability">14. Limitation of liability</h2>
      <ul>
        <li><strong>No consequential damages</strong>: To the fullest extent permitted by law, neither party will be liable for indirect, incidental, special, consequential, exemplary, punitive, or lost profits/revenue/data arising from or related to the Service.</li>
        <li><strong>Cap</strong>: Our aggregate liability for all claims arising out of or related to the Service will not exceed the greater of (a) the amounts you paid to us for the Service in the six (6) months preceding the event giving rise to liability; or (b) £100.</li>
        <li><strong>Exclusions</strong>: Nothing limits liability for death or personal injury caused by negligence, fraud, or any liability that cannot be excluded under applicable law.</li>
      </ul>

      <h2 id="term-termination">15. Term & termination</h2>
      <p>
        These Terms apply while you use the Service. We may suspend or terminate access immediately if you materially breach these Terms, cause security or legal risk, or fail to pay fees when due. Upon termination, your right to use the Service ceases; certain sections survive (including 5, 6, 7, 8, 11, 13, 14, 17).
      </p>

      <h2 id="compliance">16. Compliance</h2>
      <p>
        You will comply with all applicable laws and regulations, including export controls and sanctions. You will not use the Service in or for the benefit of embargoed persons or countries.
      </p>

      <h2 id="boilerplate">17. General</h2>
      <ul>
        <li><strong>Governing law & jurisdiction</strong>: England and Wales. Courts of England and Wales shall have exclusive jurisdiction, subject to consumer rights where applicable.</li>
        <li><strong>Assignment</strong>: You may not assign these Terms without our consent; we may assign to an affiliate or in connection with a merger, acquisition, or asset sale.</li>
        <li><strong>Severability</strong>: If any provision is unenforceable, the remainder remains in effect.</li>
        <li><strong>No waiver</strong>: Failure to enforce is not a waiver.</li>
        <li><strong>Notices</strong>: Via email, in-product, or posting to the site.</li>
        <li><strong>Entire agreement</strong>: These Terms, together with policies referenced herein, constitute the entire agreement.</li>
      </ul>

      <hr />
      <p className="small text-slate-500">
        These Terms are for general informational purposes and do not constitute legal advice. Consider a solicitor review for your specific use.
      </p>
    </main>
  );
}
